// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwtdnidxfdkmjtataacq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3dGRuaWR4ZmRrbWp0YXRhYWNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Nzc4MzMsImV4cCI6MjA2NTU1MzgzM30.mRRWEIIhnaeXP2kaKWxY7YNX-XqoCWxZJ75qCLHT7S8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);